# Generated by Django 5.0.3 on 2024-04-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('exer_date', models.DateTimeField(null=True)),
                ('exer_type', models.CharField(max_length=16)),
                ('exer_time', models.IntegerField(default=0)),
                ('exer_position', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=16)),
                ('user_mail', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=14)),
                ('user_gender', models.BooleanField(blank=True, null=True)),
                ('user_uid', models.IntegerField(default=0)),
                ('user_time_a', models.IntegerField(default=0)),
                ('user_time_w', models.IntegerField(default=0)),
                ('user_num', models.IntegerField(default=0)),
                ('user_last_login', models.DateTimeField(help_text='最后登录时间', null=True, verbose_name='最后登录时间')),
                ('user_pass_errnum', models.IntegerField(default=0, help_text='用户密码输入次数', verbose_name='用户密码输入次数')),
                ('user_last_login_error', models.DateTimeField(help_text='最后登录错误的时间戳', null=True, verbose_name='最后登录错误的时间戳')),
                ('user_lock', models.BooleanField(default=False, help_text='锁', verbose_name='锁')),
            ],
        ),
    ]
