# Generated by Django 5.0.3 on 2024-04-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mail', models.EmailField(max_length=254)),
                ('sp_pid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sp_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mail', models.EmailField(max_length=254)),
                ('sp_pid', models.IntegerField(default=0)),
                ('sp_type', models.CharField(max_length=16)),
                ('sp_date', models.DateTimeField(null=True)),
                ('sp_time_begin', models.DateTimeField(null=True)),
                ('sp_time_end', models.DateTimeField(null=True)),
                ('sp_time', models.IntegerField(default=0)),
                ('sp_location', models.CharField(max_length=128)),
                ('sp_message', models.CharField(max_length=200)),
                ('sp_love_n', models.IntegerField(default=0)),
                ('sp_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Target_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mail', models.EmailField(max_length=254)),
                ('ts_aim', models.IntegerField(default=0)),
                ('ts_aim_time', models.DateTimeField(null=True)),
                ('ts_type', models.CharField(max_length=16)),
                ('ts_remind', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Exercise_table',
        ),
    ]
