# Generated by Django 5.0.3 on 2024-05-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_community_sp_table_target_set_delete_exercise_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='target_set',
            name='ts_reminded',
            field=models.BooleanField(default=False),
        ),
    ]
