# Generated by Django 5.0.3 on 2024-05-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_target_set_ts_reminded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='sp_pid',
        ),
        migrations.AddField(
            model_name='community',
            name='Com_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='community',
            name='Comment',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='Re_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='community',
            name='is_re',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_info',
            name='user_rtime',
            field=models.DateField(help_text='注册时间', null=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_password',
            field=models.CharField(max_length=300),
        ),
    ]
