# Generated by Django 5.0.3 on 2024-05-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_community_sp_pid_community_com_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_name', models.CharField(max_length=128, null=True)),
                ('act_image', models.ImageField(upload_to='')),
                ('act_id', models.IntegerField(default=0)),
                ('act_time', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='admin_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=16)),
                ('user_mail', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=300)),
                ('user_academy', models.IntegerField(default=100)),
                ('user_uid', models.IntegerField(default=0)),
                ('user_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='user_time_w',
        ),
        migrations.AddField(
            model_name='community',
            name='com_2Agency',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='com_Agency',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='com_report',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='time',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sp_table',
            name='sp_2Agency',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sp_table',
            name='sp_Agency',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sp_table',
            name='sp_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sp_table',
            name='sp_report',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sp_table',
            name='user_uid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='target_set',
            name='user_uid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_info',
            name='user_academy',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='user_info',
            name='user_rank',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='user_info',
            name='user_sp_num',
            field=models.IntegerField(default=0),
        ),
    ]
