# Generated by Django 5.0.3 on 2024-06-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_activity_admin_info_remove_user_info_user_time_w_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp_table',
            name='user_name',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
