# Generated by Django 5.0.3 on 2024-06-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_sp_table_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='sp_pid',
            field=models.IntegerField(default=0),
        ),
    ]
