# Generated by Django 5.0.3 on 2024-06-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_community_sp_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='sp_pid',
            new_name='sp_id',
        ),
        migrations.AddField(
            model_name='community',
            name='com_username',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
