# Generated by Django 5.0.3 on 2024-06-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_sp_pid_community_sp_id_community_com_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='com_user',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
