# Generated by Django 5.0.3 on 2024-06-10 12:58

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_community_com_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp_table',
            name='sp_image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location=''), upload_to='uploads/'),
        ),
    ]
