# Generated by Django 5.0.3 on 2024-06-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_sp_table_sp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp_table',
            name='sp_message',
            field=models.CharField(max_length=2000),
        ),
    ]
