# Generated by Django 5.0.3 on 2024-06-10 13:25

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_sp_table_sp_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location=''), upload_to='uploads/')),
            ],
        ),
    ]
