# Generated by Django 5.0.3 on 2024-06-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_images_sp_id_alter_images_sp_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp_table',
            name='file_name',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
