# Generated by Django 5.0.3 on 2024-06-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_sp_table_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='file_name',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='act_image',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
