# Generated by Django 5.0.3 on 2024-06-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_activity_file_name_alter_activity_act_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='file_name',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='image_url',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
